# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-16 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=20, verbose_name='收件人')),
                ('address', models.CharField(max_length=50, verbose_name='收件地址')),
                ('receiver_phone', models.CharField(max_length=11, verbose_name='收件人电话')),
                ('isdefault', models.BooleanField(default=False, verbose_name='是否为默认地址')),
                ('postcode', models.CharField(max_length=6, verbose_name='邮编')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11, verbose_name='手机')),
                ('isactive', models.BooleanField(default=False, verbose_name='是否激活')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后活跃时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
